model:
    vq_model:
        quantizer: "vq"
        codebook_size: 4096
        latent_token_size: 1024
        n_embd: 1024
        num_rois: 450
        num_timestamp: 181
        use_l2_norm: True
        commitment_cost: 0.25
        # vit arch
        model_size: "large"
        patch_size: 16
        num_latent_tokens: 128
        # text model
        text_model_name: "gpt2"
        text_hidden_dim: null

losses:
    quantizer_weight: 1.0


optimizer:
    name: adamw 
    params:
        learning_rate: 1e-4
        beta1: 0.9
        beta2: 0.99
        weight_decay: 1e-4
        epsilon: 1e-8

lr_scheduler:
    scheduler: "cosine"
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 10_000
        end_lr: 1e-5

training:
    gradient_accumulation_steps: 1
    per_gpu_batch_size: 32
    mixed_precision: "fp16"
    enable_tf32: True
    enable_wandb: True
    use_ema: True
    seed: 42
    max_train_steps: 1_000_000
    num_generated_images: 2
    max_grad_norm: 1.0