model:
  vq_model:
      patch_size: 80
      n_embd: 768
      in_chans: 1
      num_rois: 450
      num_timestamp: 160
      enc_cls: vit_base
      attn_mode: normal
      drop_path_rate: 0.1

      add_cls_token: false
    
  lm:
      base_model: null  # will be set in the training script
      num_fmri_tokens: 900
      fmri_vocab_size: 8192  # for vq
      dropout: 0.0
      num_rois: 450
      use_fmri_lm_head: true  # use a seperate head for fMRI LM loss
      add_fmri_delimiter: true # add fmri_start and fmri_end to the input sequence

      # instruction tuning
      peft_tune: true
      use_cls_head: false
      freeze_pretrained_lora: false

      temperature: 0.7
      top_p: 0.8
      top_k: 20